version: '3.9'
services:
  postgres:
    image: postgres
    container_name: laravel_web
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
